select SEGMENT1,ORGANIZATION_CODE,PROCESS_ORGN_CODE 
 from mtl_system_itemS_b ITEM,MTL_PARAMETERS MP where 
MP.ORGANIZATION_ID=ITEM.ORGANIZATION_ID
--and 
--PROCESS_ORGN_CODE = ORGANIZATION_CODE
--AND MP.PROCESS_ORGN_CODE in ('SI','SJ')

AND SEGMENT1 in ('RE-SGM8555/17K-C1')
